# -*- coding: utf-8 -*-
"""Aula-4-modulo-1-resiliabyifood.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xEf8MSdjsSroAO82-dHm7kcE75w7cxqA
"""

print(10+10)
print(12-10)
print(12*2)
print(12/2)
print("resultados das operações matemáticas básicas")