# -*- coding: utf-8 -*-
"""exercicia-subtracao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XN-GInnTMSPkzhZjqfnJcIkv8Mxctg_W
"""

print(8-4)
print("resultado da subtração de 8 e 4")