# -*- coding: utf-8 -*-
"""exercicio-divisao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IRbTm2O1Mk2C6WhqSySBgy1yv78p4XmM
"""

print(8/4)
print("resultado da divisão de 8 por 4")