# -*- coding: utf-8 -*-
"""exercicio-multiplicacao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bt6P9NkbXSk-_bqxFiIg-rLHEwoIZ0uE
"""

print(8*4)
print("resultado da multiplicação de 8 por 4")