# -*- coding: utf-8 -*-
"""exercicio-adicao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ul0OZ0l0AxyAXZP78g6mRwrdEmiB6Kf9
"""

print(8+4)
print("resultado da adição de 8 e 4")